---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Ensure zaqar service
  keystone:
    command: "ensure_service"
    endpoint: "{{ keystone_service_adminurl }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    service_name: "{{ zaqar_service_name }}"
    service_type: "{{ zaqar_service_type }}"
    description: "{{ zaqar_service_description }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_service
  until: add_service|success
  retries: 5
  delay: 2
  no_log: True
  tags:
    - zaqar-setup
    - zaqar-service-add

- name: Ensure service project
  keystone:
    command: ensure_project
    project_name: "{{ zaqar_service_tenant_name }}"
    region_name: "{{ zaqar_service_region }}"
    endpoint: "{{ keystone_service_adminurl }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  no_log: True
  tags:
    - zaqar-setup
    - zaqar-service-add

- name: Ensure zaqar user
  keystone:
    command: "ensure_user"
    endpoint: "{{ keystone_service_adminurl }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    user_name: "{{ zaqar_service_user_name }}"
    tenant_name: "{{ zaqar_service_tenant_name }}"
    password: "{{ zaqar_service_user_password }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_service
  until: add_service|success
  retries: 5
  delay: 10
  no_log: True
  tags:
    - zaqar-setup
    - zaqar-service-add

- name: Ensure zaqar user to admin role
  keystone:
    command: "ensure_user_role"
    endpoint: "{{ keystone_service_adminurl }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    user_name: "{{ zaqar_service_user_name }}"
    tenant_name: "{{ zaqar_service_project_name }}"
    role_name: "{{ zaqar_service_role_name }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_admin_role
  until: add_admin_role|success
  retries: 5
  delay: 10
  no_log: True
  tags:
    - zaqar-service-add
    - zaqar-setup


# Create an endpoint
- name: Ensure zaqar endpoint
  keystone:
    command: "ensure_endpoint"
    endpoint: "{{ keystone_service_adminurl }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    region_name: "{{ zaqar_service_region }}"
    service_name: "{{ zaqar_service_name }}"
    service_type: "{{ zaqar_service_type }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
    endpoint_list:
      - url: "{{ zaqar_service_publicurl }}"
        interface: "public"
      - url: "{{ zaqar_service_adminurl }}"
        interface: "admin"
      - url: "{{ zaqar_service_internalurl }}"
        interface: "internal"
  register: add_service
  until: add_service|success
  retries: 5
  delay: 10
  no_log: True
  tags:
    - zaqar-setup
    - zaqar-service-add
